[build]
    command = "yarn build"
    publish = "dist"
    functions = "functions"

[build.environment]
    NODE_VERSION = "16"
    YARN_VERSION = "1.22"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200